version: '3'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  node:
    build: .
    ports:
      - "8000:3000"    
    links:
      - redis
      - mongo
    depends_on:
      - mongo
  redis:
    image: redis
  angular:
    image: guitars-frontend
    ports:
      - "80:80"
    links:
      - node